version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD"
      - "POSTGRES_USER"
      - "POSTGRES_DB"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"






