version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD"
      - "POSTGRES_USER"
      - "POSTGRES_DB"
    networks:
      - my-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - my-network
  auth:
    build:
      context: .
#      dockerfile: Dockerfile
    image: auth-image
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=AuthApp
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    networks:
      my-network:
        aliases:
          - flask-app

  tests:
    image: auth-image
    entrypoint: ["python", "-m", "pytest", "tests/functional/src"]
    depends_on:
      - postgres
      - redis
    networks:
      - my-network

  nginx:
    container_name: nginx
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - auth
    networks:
      - my-network


networks:
  my-network:




